apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-short
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-short
  template:
    metadata:
      labels:
        app: queue-short
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: queue-short
        # image: ghcr.io/lxbach10012004/custom-erpnext:1.0.0
        image: asia-southeast1-docker.pkg.dev/erpnext-ptuddn-454813/custom-erp/custom-erpnext:1.0.0
        command:
        - bench
        - worker
        - --queue
        - short,default
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      # volumes:
      # - name: sites
      #   hostPath:
      #     path: "/mnt/data/sites"
      #     type: DirectoryOrCreate
      # - name: logs
      #   hostPath:
      #     path: "/mnt/data/logs"
      #     type: DirectoryOrCreate
      
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: sites
      - name: logs
        persistentVolumeClaim:
          claimName: logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-long
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-long
  template:
    metadata:
      labels:
        app: queue-long
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: queue-long
        # image: ghcr.io/lxbach10012004/custom-erpnext:1.0.0
        image: asia-southeast1-docker.pkg.dev/erpnext-ptuddn-454813/custom-erp/custom-erpnext:1.0.0
        command:
        - bench
        - worker
        - --queue
        - long,default,short
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      # volumes:
      # - name: sites
      #   hostPath:
      #     path: "/mnt/data/sites"
      #     type: DirectoryOrCreate
      # - name: logs
      #   hostPath:
      #     path: "/mnt/data/logs"
      #     type: DirectoryOrCreate
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: sites
      - name: logs
        persistentVolumeClaim:
          claimName: logs