name: Build, Push Docker Image, and Deploy to GKE

on:
  push:
    branches:
      - main # Thực hiện khi có push vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: code checkout
        uses: actions/checkout@v2

      # Setup Google Cloud SDK
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      # Authenticate Docker with Google Cloud
      - name: Authenticate Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      # Build and push the Docker image
      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/erpnext-ptuddn-454813/demo/nginx:latest .
          docker push asia-southeast1-docker.pkg.dev/erpnext-ptuddn-454813/demo/nginx:latest

      # Deploy to GKE
      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials cicd --region asia-southeast1
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
          kubectl apply -f resources.yaml
